---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: qa
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  environments_path: test/integration/environments

platforms:
  # default opscode-centos-5.10 box prior to chef installation
  - name: centos-5.10-opscode
    driver:
      box: opscode-centos-5.10

  # default opscode-centos-6.5 box prior to chef installation
  - name: centos-6.5-opscode
    driver:
      box: opscode-centos-6.5

  # locally-provisioned opscode-centos-5.10 box with omnibus chef 11.8.2
  - name: centos-5.10-chef-11.8.2
    driver:
      box: opscode-centos-5.10-chef-11.8.2

  # locally-provisioned opscode-centos-6.5 box with omnibus chef 11.8.2
  - name: centos-6.5-chef-11.8.2
    driver:
      box: opscode-centos-6.5-chef-11.8.2

suites:
  - name: default
    run_list:
      - 'recipe[mysql::server]'   # need to install mysql-server first
      - 'recipe[automysqlbackup]'
    attributes: {}
